name: 'assurplus'
version: '1.0.0'
config-version: 2

profile: 'assurplus'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  assurplus:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

