assurplus:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres_db
      port: 5432
      user: assurplus
      pass: assurplus
      dbname: assurplus
      schema: staging
      threads: 4
