version: 2

sources:
  - name: raw
    description: Raw data loaded from CSV files
    database: assurplus
    schema: raw
    config:
      severity: warn
    tables:
      - name: leads
        description: "{{ doc('raw_leads') }}"
        columns:
          - name: lead_id
            description: "{{ doc('raw_leads_lead_id') }}"
            tests:
              - not_null
              - unique
          
          - name: telephone
            description: "{{ doc('raw_leads_telephone') }}"
            tests:
              - not_null
              - unique
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^[0-9]{11}$"
          
          - name: email
            description: "{{ doc('raw_leads_email') }}"
            tests:
              - not_null
              - unique
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
          
          - name: date_creation
            description: "{{ doc('raw_leads_date_creation') }}"
            tests:
              - not_null
              # Range check done in staging after type casting
          
          - name: commercial_assigne_id
            description: "{{ doc('raw_leads_commercial_assigne_id') }}"
            tests:
              - relationships:
                  to: source('raw', 'commerciaux')
                  field: id
                  where: "commercial_assigne_id != '' AND commercial_assigne_id IS NOT NULL"

      - name: appels
        description: "{{ doc('raw_appels') }}"
        columns:
          - name: appel_id
            description: "{{ doc('raw_appels_appel_id') }}"
            tests:
              - not_null
              - unique
          
          - name: lead_id
            description: "{{ doc('raw_appels_lead_id') }}"
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'leads')
                  field: lead_id
          
          - name: commercial_id
            description: "{{ doc('raw_appels_commercial_id') }}"
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'commerciaux')
                  field: id
          
          - name: date_appel
            description: "{{ doc('raw_appels_date_appel') }}"
            tests:
              - not_null
          
          - name: duree_secondes
            description: "{{ doc('raw_appels_duree_secondes') }}"
            tests:
              - not_null
              # Range check done in staging after type casting
          
          - name: statut
            description: "{{ doc('raw_appels_statut') }}"
            tests:
              - not_null
              - accepted_values:
                  values: ['connected', 'no_answer', 'busy', 'messagerie', 'faux_numero', 'repondeur']

      - name: contrats
        description: "{{ doc('raw_contrats') }}"
        columns:
          - name: contrat_id
            description: "{{ doc('raw_contrats_contrat_id') }}"
            tests:
              - not_null
              - unique
          
          - name: lead_id
            description: "{{ doc('raw_contrats_lead_id') }}"
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'leads')
                  field: lead_id
          
          - name: commercial_id
            description: "{{ doc('raw_contrats_commercial_id') }}"
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'commerciaux')
                  field: id
          
          - name: date_signature
            description: "{{ doc('raw_contrats_date_signature') }}"
            tests:
              - not_null
              # Custom test for temporal inconsistencies will be in tests/ directory
          
          - name: prime_annuelle
            description: "{{ doc('raw_contrats_prime_annuelle') }}"
            tests:
              - not_null
              # Range check done in staging after type casting
          
          - name: statut
            description: "{{ doc('raw_contrats_statut') }}"
            tests:
              - not_null
              - accepted_values:
                  values: ['actif', 'annule', 'en_attente']

      - name: commerciaux
        description: "{{ doc('raw_commerciaux') }}"
        columns:
          - name: id
            description: "{{ doc('raw_commerciaux_id') }}"
            tests:
              - not_null
              - unique
          
          - name: email
            description: "{{ doc('raw_commerciaux_email') }}"
            tests:
              - not_null
              - unique
          
          - name: nom
            description: "{{ doc('raw_commerciaux_nom') }}"
            tests:
              - not_null
