version: 2

models:
  - name: stg_leads
    description: "{{ doc('stg_leads') }}"
    columns:
      - name: lead_id
        description: "{{ doc('stg_leads_lead_id') }}"
        tests:
          - unique
          - not_null

      - name: email
        description: "{{ doc('stg_leads_email') }}"
        tests:
          - not_null
          - unique
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"

      - name: telephone
        description: "{{ doc('stg_leads_telephone') }}"
        tests:
          - not_null
          - unique
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "^[0-9]{11}$"

      - name: date_creation
        description: "{{ doc('stg_leads_date_creation') }}"
        tests:
          - not_null
          # Date range validated in raw sources; staging data is already cleaned

      - name: commercial_assigne_id
        description: "{{ doc('stg_leads_commercial_assigne_id') }}"
        tests:
          - relationships:
              to: ref('stg_commerciaux')
              field: commercial_id

  - name: stg_appels
    description: "{{ doc('stg_appels') }}"
    columns:
      - name: appel_id
        description: "{{ doc('stg_appels_appel_id') }}"
        tests:
          - unique
          - not_null

      - name: lead_id
        description: "{{ doc('stg_appels_lead_id') }}"
        tests:
          - not_null
          - relationships:
              to: ref('stg_leads')
              field: lead_id

      - name: commercial_id
        description: "{{ doc('stg_appels_commercial_id') }}"
        tests:
          - not_null
          - relationships:
              to: ref('stg_commerciaux')
              field: commercial_id

      - name: date_appel
        description: "{{ doc('stg_appels_date_appel') }}"
        tests:
          - not_null

      - name: duree_secondes
        description: "{{ doc('stg_appels_duree_secondes') }}"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 7200

      - name: statut
        description: "{{ doc('stg_appels_statut') }}"
        tests:
          - not_null
          - accepted_values:
              values: ['connected', 'no_answer', 'busy', 'messagerie', 'faux_numero', 'repondeur']

  - name: stg_contrats
    description: "{{ doc('stg_contrats') }}"
    columns:
      - name: contrat_id
        description: "{{ doc('stg_contrats_contrat_id') }}"
        tests:
          - unique
          - not_null

      - name: lead_id
        description: "{{ doc('stg_contrats_lead_id') }}"
        tests:
          - not_null
          - relationships:
              to: ref('stg_leads')
              field: lead_id

      - name: commercial_id
        description: "{{ doc('stg_contrats_commercial_id') }}"
        tests:
          - not_null
          - relationships:
              to: ref('stg_commerciaux')
              field: commercial_id

      - name: date_signature
        description: "{{ doc('stg_contrats_date_signature') }}"
        tests:
          - not_null

      - name: prime_annuelle
        description: "{{ doc('stg_contrats_prime_annuelle') }}"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 5000

      - name: statut
        description: "{{ doc('stg_contrats_statut') }}"
        tests:
          - not_null
          - accepted_values:
              values: ['actif', 'annule', 'en_attente']

  - name: stg_commerciaux
    description: "{{ doc('stg_commerciaux') }}"
    columns:
      - name: commercial_id
        description: "{{ doc('stg_commerciaux_commercial_id') }}"
        tests:
          - unique
          - not_null

      - name: email
        description: "{{ doc('stg_commerciaux_email') }}"
        tests:
          - unique
          - not_null

      - name: nom
        description: "{{ doc('stg_commerciaux_nom') }}"
        tests:
          - not_null
