version: 2

models:
  - name: stg_leads
    description: Cleaned and typed lead data
    columns:
      - name: lead_id
        description: Unique identifier for each lead
        tests:
          - unique
          - not_null

      - name: email
        description: Lead email address
        tests:
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
              config:
                severity: warn

      - name: telephone
        description: Lead phone number
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "^[0-9]{11}$"
              config:
                severity: warn

      - name: date_creation
        description: Lead creation timestamp
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: "2026-01-01"
              max_value: "2026-01-31"

      - name: commercial_assigne_id
        description: Assigned sales rep ID
        tests:
          - relationships:
              to: ref('stg_commerciaux')
              field: commercial_id
              config:
                severity: warn

  - name: stg_appels
    description: Cleaned and typed call data
    columns:
      - name: appel_id
        description: Unique identifier for each call
        tests:
          - unique
          - not_null

      - name: lead_id
        description: Lead being called
        tests:
          - not_null
          - relationships:
              to: ref('stg_leads')
              field: lead_id
              config:
                severity: error
                error_if: ">10"
                warn_if: ">0"

      - name: commercial_id
        description: Sales rep making the call
        tests:
          - not_null
          - relationships:
              to: ref('stg_commerciaux')
              field: commercial_id

      - name: date_appel
        description: Call timestamp
        tests:
          - not_null

      - name: duree_secondes
        description: Call duration in seconds
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 7200
              config:
                severity: warn

      - name: statut
        description: Call outcome status
        tests:
          - not_null
          - accepted_values:
              values: ['connected', 'no_answer', 'busy', 'messagerie', 'faux_numero', 'repondeur']

  - name: stg_contrats
    description: Cleaned and typed contract data
    columns:
      - name: contrat_id
        description: Unique identifier for each contract
        tests:
          - unique
          - not_null

      - name: lead_id
        description: Lead who signed
        tests:
          - not_null
          - relationships:
              to: ref('stg_leads')
              field: lead_id

      - name: commercial_id
        description: Sales rep who closed the deal
        tests:
          - not_null
          - relationships:
              to: ref('stg_commerciaux')
              field: commercial_id

      - name: date_signature
        description: Contract signature date
        tests:
          - not_null

      - name: prime_annuelle
        description: Annual premium amount
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10000

      - name: statut
        description: Contract status
        tests:
          - not_null
          - accepted_values:
              values: ['actif', 'annule', 'en_attente']

  - name: stg_commerciaux
    description: Cleaned and typed sales team data
    columns:
      - name: commercial_id
        description: Unique identifier for each sales rep
        tests:
          - unique
          - not_null

      - name: email
        description: Sales rep email
        tests:
          - unique
          - not_null

      - name: nom
        description: Sales rep name
        tests:
          - not_null
