version: 2

models:
  - name: commercial_performance
    description: Performance metrics aggregated by sales rep.
    columns:
      - name: commercial_id
        description: Sales rep identifier
        tests:
          - unique
          - not_null

      - name: taux_joignabilite_pct
        description: Percentage of calls that connected
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100

      - name: taux_conversion_pct
        description: Percentage of contacted leads that converted
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100

  - name: contrats_stat
    description: Sales statistics for leads who signed contracts.
    columns:
      - name: contrat_id
        description: Contract identifier
        tests:
          - unique
          - not_null
      
      - name: lead_id
        description: Lead identifier
        tests:
          - not_null
          - relationships:
              to: ref('stg_leads')
              field: lead_id

      - name: delai_premier_appel_signature
        description: Days between first call and signature
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 365
              config:
                severity: warn

      - name: nombre_appels_avant_signature
        description: Number of calls before the lead signed
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
              config:
                severity: warn
